apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
      app1: app
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 500Mi        
        ports:
        - containerPort: 80
