apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: guestbook-ui
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: guestbook-ui
    
  targetCPUUtilizationPercentage: 60
