apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: test-1
spec:
  scaleRef:
    kind: ReplicaSet
    name: guestbook-ui
  minReplicas: 3
  maxReplicas: 10
  cpuUtilization:
    targetPercentage: 50
